"use client";

import { ArrowUpRight, Layers3, Orbit, Plus, Rotate3D, Sparkles, Target } from "lucide-react";
import { StylePageFooter, StylePageHeader } from "@/src/components/StylePageChrome";

export default function SpatialUIPage() {
  return (
    <main className="spatial-page"><StylePageHeader /><section className="spatial-hero" id="scene"><div className="spatial-copy"><p className="spatial-eyebrow"><span /> SPATIAL WORKSPACE / 03</p><h1>Move ideas<br /><em>into orbit.</em></h1><p className="spatial-lede">A spatial canvas for teams who think in dimensions, not documents.</p><div className="spatial-hero-buttons"><a href="#layers" className="spatial-button">Enter the room <ArrowUpRight size={16} /></a><span><Rotate3D size={16} /> Drag to explore</span></div></div><div className="spatial-scene"><div className="spatial-ring spatial-ring-one" /><div className="spatial-ring spatial-ring-two" /><div className="spatial-orb"><div /><span>01</span></div><div className="spatial-float spatial-float-a"><span>LIVE NODE</span><strong>Product<br />direction</strong><small>UP 42.8%</small></div><div className="spatial-float spatial-float-b"><Target size={17} /><span>FOCUS VECTOR</span><strong>North star<br />confirmed</strong></div><span className="spatial-scene-coord">19.4326 N<br />99.1332 W</span></div></section><section className="spatial-layers" id="layers"><div className="spatial-section-title"><span>01 - SHARED SPACE</span><h2>Everything<br />has a <em>place.</em></h2></div><div className="spatial-layer-stack"><article className="spatial-layer spatial-layer-back"><span>03 / context</span><h3>See the whole field.</h3><Layers3 size={25} /></article><article className="spatial-layer spatial-layer-mid"><span>02 / connections</span><h3>Connect the signals.</h3><div className="spatial-mini-nodes"><i /><i /><i /><i /></div></article><article className="spatial-layer spatial-layer-front"><span>01 / now</span><h3>Work on what matters.</h3><div className="spatial-plus"><Plus size={19} /></div></article></div></section><section className="spatial-mission" id="mission"><div className="spatial-mission-orb"><Sparkles size={28} /><span>ONE<br />CLEAR<br />MOVE</span></div><div><p className="spatial-eyebrow">THE ORBITAL PRINCIPLE</p><h2>Less friction.<br /><em>More dimension.</em></h2><p>Give every thought a surface, every surface a relationship, and every relationship a direction.</p><a href="mailto:hola@aionsite.com">Create your room <ArrowUpRight size={16} /></a></div></section><StylePageFooter /></main>
  );
}
