"use client";

import { StylePageFooter, StylePageHeader } from "@/src/components/StylePageChrome";
import { ArrowUpRight, Check, ChevronRight, CircleDot, Command, Menu, MoveUpRight, Play, Zap } from "lucide-react";

const metrics = [{ value: "24.8k", label: "visitas activas", trend: "+18.4%" }, { value: "8.6%", label: "conversión", trend: "+2.1%" }, { value: "4.9/5", label: "satisfacción", trend: "+0.6" }];

export default function SpecialUIPage() {
  return (
    <main className="special-page">
      <StylePageHeader />
      <section className="special-hero"><div className="special-hero-copy"><div className="special-status"><span /> sistema en vivo <span className="special-status-time">09:41:28 UTC</span></div><h1>Interfaces<br /><i>con</i> intención<span>.</span></h1><p>Diseñamos sistemas digitales que convierten complejidad en movimiento claro.</p><div className="special-hero-actions"><a className="special-primary" href="#sistema">Ver el sistema <MoveUpRight size={16} /></a><button className="special-play"><span><Play size={12} fill="currentColor" /></span> Ver manifiesto</button></div></div><div className="special-signal"><div className="special-signal-head"><span>LIVE SIGNAL / 001</span><span>+ 34.7%</span></div><div className="special-signal-graph"><div className="special-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><svg viewBox="0 0 520 250" preserveAspectRatio="none" role="img" aria-label="Gráfica de crecimiento"><defs><linearGradient id="signalFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#d9ff5f" stopOpacity=".3" /><stop offset="1" stopColor="#d9ff5f" stopOpacity="0" /></linearGradient></defs><path d="M0 210 C35 205 40 165 74 177 S110 195 130 140 S164 154 192 112 S220 132 247 98 S281 120 310 88 S343 95 365 57 S406 89 430 48 S461 67 520 13 V250 H0Z" fill="url(#signalFill)" /><path d="M0 210 C35 205 40 165 74 177 S110 195 130 140 S164 154 192 112 S220 132 247 98 S281 120 310 88 S343 95 365 57 S406 89 430 48 S461 67 520 13" fill="none" stroke="#d9ff5f" strokeWidth="3" /></svg></div><div className="special-signal-foot"><span>JAN</span><span>FEB</span><span>MAR</span><span>APR</span><span>MAY</span><span>JUN</span></div></div></section>
      <section className="special-marquee"><span>STRATEGY</span><CircleDot size={14} /><span>DESIGN</span><CircleDot size={14} /><span>ENGINEERING</span><CircleDot size={14} /><span>STRATEGY</span></section>
      <section className="special-system" id="sistema"><div className="special-section-label"><span>01</span><span>THE NODO METHOD</span></div><div className="special-system-body"><div><h2>Lo especial<br />está en el <em>flujo.</em></h2><p>Una mirada conectada para que cada decisión de producto tenga una razón, un ritmo y una señal que puedas medir.</p><a className="special-text-link" href="#senales">Conocer el método <ChevronRight size={17} /></a></div><div className="special-metric-grid">{metrics.map((metric) => <article key={metric.label}><span className="special-metric-trend">{metric.trend}</span><strong>{metric.value}</strong><span>{metric.label}</span></article>)}</div></div></section>
      <section className="special-cards" id="senales"><article className="special-feature-card"><div className="special-feature-icon"><Zap size={20} /></div><span>02 / SIGNALS</span><h3>De la intuición<br />a la señal.</h3><p>Detecta lo que importa antes de que se convierta en ruido.</p><a href="#contacto"><ArrowUpRight size={18} /></a></article><article className="special-feature-card special-feature-dark"><div className="special-feature-icon"><Check size={20} /></div><span>03 / DELIVERY</span><h3>Menos decks.<br /><i>Más avance.</i></h3><p>Ideas convertidas en sistemas que el equipo puede usar hoy.</p><a href="#contacto"><ArrowUpRight size={18} /></a></article></section>
      <section className="special-contact" id="contacto"><div><span>READY WHEN YOU ARE</span><h2>Hagamos algo<br /><em>especial.</em></h2></div><a className="special-contact-button" href="mailto:hola@aionsite.com">Abrir conversación <ArrowUpRight size={18} /></a></section><StylePageFooter />
    </main>
  );
}
