"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Menu, MessageCircleMore, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { CmsContent } from "@/src/cms/types";

export function FutureStyleHome({ content }: { content: CmsContent }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const { base, sections } = content;
  const projects = sections.portfolio.data.slice(0, 3);

  useEffect(() => {
    const targets = [...document.querySelectorAll<HTMLElement>("[data-future-reveal]")];
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); }
    }), { threshold: 0.12, rootMargin: "0px 0px -10%" });
    targets.forEach((target) => observer.observe(target));
    return () => observer.disconnect();
  }, []);

  return (
    <main className="future-aion min-h-screen overflow-hidden bg-[#070b12] text-white">
      <header className="fixed inset-x-0 top-0 z-50 px-4 py-4 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between rounded-full border border-white/15 bg-[#070b12]/55 px-5 py-3 backdrop-blur-xl"><Link href="/future" className="font-display text-xl tracking-[-.06em]">Aion<span className="text-[#ff6a3d]">Site</span></Link><nav className="hidden items-center gap-7 text-sm text-white/75 lg:flex"><a href="#servicios" className="transition-colors hover:text-white">Servicios</a><Link href="/proyectos" className="transition-colors hover:text-white">Proyectos</Link><a href="#historias" className="transition-colors hover:text-white">Historias</a><a href={sections.header.data.whatsappLink} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-semibold text-[#070b12] transition-transform hover:-translate-y-0.5"><MessageCircleMore size={15} /> Cotizar</a></nav><button type="button" onClick={() => setMenuOpen((value) => !value)} className="rounded-full border border-white/15 p-2 lg:hidden" aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"}>{menuOpen ? <X size={18} /> : <Menu size={18} />}</button></div>{menuOpen && <div className="mx-auto mt-2 flex max-w-6xl flex-col gap-4 rounded-3xl border border-white/10 bg-[#0c131d] p-6 text-sm lg:hidden"><a href="#servicios" onClick={() => setMenuOpen(false)}>Servicios</a><Link href="/proyectos">Proyectos</Link><a href="#historias" onClick={() => setMenuOpen(false)}>Historias</a><a href={sections.header.data.whatsappLink} target="_blank" rel="noreferrer">Cotizar →</a></div>}</header>

      <section className="future-hero relative flex min-h-screen items-center justify-center px-5 pb-16 pt-28 text-center sm:px-10"><div className="future-hero-media absolute inset-0 bg-[url('/media/aionsite-tech-background.gif')] bg-cover bg-center opacity-60"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_38%,rgba(255,106,61,.35),transparent_30%),linear-gradient(180deg,rgba(7,11,18,.4),#070b12_92%)]"/><div className="relative z-10 mx-auto max-w-5xl"><p className="future-reveal mb-6 text-xs uppercase tracking-[.28em] text-[#ffb09a]">AionSite / crecimiento digital</p><h1 className="future-reveal font-[Georgia,serif] text-[clamp(3.5rem,9vw,8rem)] leading-[.88] tracking-[-.07em]">Tu presencia online, <em className="font-normal text-[#ff8b68]">reimaginada.</em></h1><p className="future-reveal mx-auto mt-8 max-w-2xl text-lg leading-relaxed text-white/75 sm:text-xl">Sitios web, tiendas y SEO con la claridad necesaria para ayudarte a avanzar.</p><div className="future-reveal mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><a href={sections.header.data.whatsappLink} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#070b12] transition-transform hover:-translate-y-1">Encuentra tu siguiente paso <ArrowRight size={17}/></a><a href="#servicios" className="text-sm text-white/75 underline decoration-[#ff6a3d] decoration-2 underline-offset-8">Ver cómo funciona</a></div><div className="future-reveal mx-auto mt-20 grid max-w-3xl grid-cols-2 border-y border-white/15 py-5 text-left sm:grid-cols-4">{["Diseño con intención", "SEO que se mide", "IA responsable", "Soporte continuo"].map((item, index) => <div key={item} className="border-white/15 px-3 py-2 text-xs text-white/60 sm:border-r last:border-0"><span className="mb-2 block text-2xl text-[#ff8b68]">0{index + 1}</span>{item}</div>)}</div></div><div className="absolute bottom-6 left-1/2 -translate-x-1/2 text-xs uppercase tracking-[.25em] text-white/45">Desplaza para explorar</div></section>

      <section id="servicios" className="future-dark-section bg-[#070b12] px-5 py-24 sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto max-w-6xl"><div data-future-reveal className="future-reveal mb-14 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[.25em] text-[#ff8b68]">Juntos llegamos más lejos</p><h2 className="mt-5 max-w-4xl font-[Georgia,serif] text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">Una presencia digital que trabaja contigo.</h2></div><p className="max-w-xs text-sm leading-relaxed text-white/55">Todo lo que necesitas para que tu negocio se vea, se entienda y se elija.</p></div><div className="future-service-track flex snap-x gap-5 overflow-x-auto pb-5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{[{title:"Hecho para expertos", text:"Tu estrategia convertida en una experiencia clara y memorable."},{title:"Nunca te quedas solo", text:"Acompañamiento, mantenimiento y decisiones respaldadas por datos."},{title:"Diseñado para la vida real", text:"Páginas que se adaptan a tu operación, tu equipo y tus clientes."},{title:"Impulso que permanece", text:"SEO, contenido y tecnología que siguen generando oportunidades."}].map((service,index)=><article data-future-reveal key={service.title} className="future-reveal future-service-card min-w-[82vw] snap-start rounded-[1.75rem] border border-white/10 bg-gradient-to-br from-white/[.12] to-white/[.025] p-7 sm:min-w-[38vw] lg:min-w-0 lg:flex-1"><div className="mb-20 flex items-center justify-between"><span className="text-sm text-[#ff8b68]">0{index+1}</span><span className="flex h-10 w-10 items-center justify-center rounded-full border border-white/15 text-white/70"><ArrowUpRight size={17}/></span></div><h3 className="font-[Georgia,serif] text-3xl leading-none tracking-[-.04em]">{service.title}</h3><p className="mt-4 text-sm leading-relaxed text-white/55">{service.text}</p></article>)}</div></div></section>

      <section data-future-reveal className="future-reveal bg-[#f2efe8] px-5 py-24 text-[#10151b] sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-xs uppercase tracking-[.25em] text-[#e95e39]">Un roadmap único para tu negocio</p><h2 className="mt-5 max-w-xl font-[Georgia,serif] text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">La ruta cambia. Tu dirección permanece.</h2><p className="mt-7 max-w-lg text-lg leading-relaxed text-[#10151b]/65">Partimos de tus objetivos, tu realidad y tus clientes. Después convertimos todo eso en una presencia que puede crecer contigo.</p><a href={sections.header.data.whatsappLink} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#10151b] px-5 py-3 text-sm font-semibold text-white">Empezar conversación <ArrowUpRight size={16}/></a></div><div className="future-profile-card relative overflow-hidden rounded-[2rem] bg-[#17222b] p-7 text-white sm:p-10"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#ff6a3d]/80 blur-2xl"/><div className="relative z-10"><p className="text-xs uppercase tracking-[.2em] text-[#ffb09a]">AionSite / tu mapa</p><div className="mt-20 grid gap-5 sm:grid-cols-2"><div><p className="text-xs text-white/45">Objetivo</p><p className="mt-2 text-xl">Ser fácil de elegir</p></div><div><p className="text-xs text-white/45">Experiencia</p><p className="mt-2 text-xl">Clara y confiable</p></div><div><p className="text-xs text-white/45">Sistema</p><p className="mt-2 text-xl">Web + SEO + IA</p></div><div><p className="text-xs text-white/45">Siguiente acción</p><p className="mt-2 text-xl text-[#ff9e80]">Crecer con intención</p></div></div></div></div></div></section>

      <section id="historias" data-future-reveal className="future-reveal bg-[#070b12] px-5 py-24 text-white sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-xs uppercase tracking-[.25em] text-[#ff8b68]">Historias reales</p><h2 className="mt-5 font-[Georgia,serif] text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">Resultados que se sienten.</h2><p className="mx-auto mt-6 max-w-xl text-white/55">Una buena experiencia no solo se ve bien: ayuda a mantener el rumbo.</p></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[{quote:"Ahora podemos explicar nuestro valor en segundos.",name:"Molotes",meta:"Cliente AionSite"},{quote:"La web dejó de ser una tarjeta y se volvió un canal.",name:"Search Atlas",meta:"Proyecto digital"},{quote:"Tenemos una base clara para seguir creciendo.",name:"LinkGraph",meta:"Optimización web"}].map((story)=><article data-future-reveal key={story.name} className="future-reveal rounded-[1.5rem] border border-white/10 bg-white/[.05] p-7"><div className="mb-16 text-5xl text-[#ff8b68]">“</div><p className="min-h-24 font-[Georgia,serif] text-2xl leading-tight">{story.quote}</p><div className="mt-8 border-t border-white/10 pt-4"><p className="font-semibold">{story.name}</p><p className="mt-1 text-xs text-white/45">{story.meta}</p></div></article>)}</div></div></section>

      <section data-future-reveal className="future-reveal bg-[#f2efe8] px-5 py-24 text-[#10151b] sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-6"><div><p className="text-xs uppercase tracking-[.25em] text-[#e95e39]">Proyectos</p><h2 className="mt-5 font-[Georgia,serif] text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">Hechos para avanzar.</h2></div><Link href="/proyectos" className="hidden items-center gap-2 text-sm font-semibold sm:flex">Ver todos <ArrowUpRight size={16}/></Link></div><div className="mt-12 grid gap-5 md:grid-cols-3">{projects.map((project,index)=><Link data-future-reveal key={project.title} href={project.url} target="_blank" rel="noreferrer" className={`future-reveal group ${index===1?"md:translate-y-10":""}`}><div className="relative aspect-[1.1] overflow-hidden rounded-[1.5rem] bg-[#d8d2c7]"><Image src={project.image} alt={project.title} fill className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><span className="absolute right-4 top-4 flex h-10 w-10 items-center justify-center rounded-full bg-white text-[#10151b] transition-transform group-hover:rotate-45"><ArrowUpRight size={16}/></span><div className="absolute bottom-5 left-5 text-white"><p className="text-xs uppercase tracking-[.18em] text-white/65">{project.category}</p><p className="mt-1 font-[Georgia,serif] text-2xl">{project.title}</p></div></div></Link>)}</div></div></section>

      <section data-future-reveal className="future-reveal px-5 pb-8 pt-8 sm:px-10 lg:px-16"><div className="mx-auto max-w-6xl rounded-[2rem] bg-[#ff6a3d] px-7 py-16 text-white sm:px-12 lg:px-20 lg:py-24"><p className="text-xs uppercase tracking-[.25em] text-white/70">Encuentra tu siguiente paso</p><div className="mt-6 grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><h2 className="max-w-4xl font-[Georgia,serif] text-5xl leading-[.9] tracking-[-.06em] sm:text-8xl">Haz que te encuentren.</h2><a href={sections.header.data.whatsappLink} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 rounded-full bg-[#10151b] px-6 py-4 text-sm font-semibold">Hablar con AionSite <ArrowUpRight size={17}/></a></div></div></section>
      <footer className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-8 text-xs text-white/45 sm:flex-row sm:justify-between sm:px-10 lg:px-16"><span>{base.name} / diseño web, SEO e IA</span><span>© {new Date().getFullYear()} AionSite</span></footer>
    </main>
  );
}
