"use client";

import Image from "next/image";
import Link from "next/link";
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { ArrowLeft, ArrowRight, ArrowUpRight, Menu, MessageCircleMore, X } from "lucide-react";
import { useRef, useState } from "react";
import type { CmsContent } from "@/src/cms/types";

function ScaleSection({ children, className = "", id }: { children: React.ReactNode; className?: string; id?: string }) {
  const ref = useRef<HTMLElement>(null);
  const reduce = useReducedMotion();
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] });
  const scale = useTransform(scrollYProgress, [0, 0.45, 1], reduce ? [1, 1, 1] : [0.88, 1, 0.9]);
  const opacity = useTransform(scrollYProgress, [0, 0.25, 0.72, 1], reduce ? [1, 1, 1, 1] : [0.35, 1, 1, 0.42]);
  return <motion.section id={id} ref={ref} style={{ scale, opacity }} className={`future-motion-section ${className}`}>{children}</motion.section>;
}

const services = [
  ["Hecho para expertos", "Tu estrategia convertida en una experiencia clara y memorable."],
  ["Nunca te quedas solo", "Acompañamiento, mantenimiento y decisiones respaldadas por datos."],
  ["Diseñado para la vida real", "Páginas que se adaptan a tu operación, tu equipo y tus clientes."],
  ["Impulso que permanece", "SEO, contenido y tecnología que siguen generando oportunidades."],
];

function FinalStickyCta({ whatsapp }: { whatsapp: string }) {
  return <section className="future-final-cta relative z-0 -mt-[18vh] min-h-[86vh] px-5 pb-24 pt-[28vh] sm:px-10 lg:px-16">
    <div className="sticky top-0 flex min-h-[58vh] items-center">
      <motion.div initial={{ opacity: 0, y: 70, scale: 0.94 }} whileInView={{ opacity: 1, y: 0, scale: 1 }} viewport={{ once: true, amount: 0.38 }} transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }} className="mx-auto w-full max-w-6xl rounded-[2rem] bg-[#ff6a3d] px-7 py-16 text-white shadow-[0_-30px_80px_rgba(255,106,61,.12)] sm:px-12 lg:px-20 lg:py-24">
        <p className="text-xs uppercase tracking-[.25em] text-white/70">Encuentra tu siguiente paso</p>
        <h2 className="mt-6 max-w-4xl font-[Georgia,serif] text-5xl leading-[.9] tracking-[-.06em] sm:text-8xl">Haz que te encuentren.</h2>
        <a href={whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#10151b] transition-transform hover:-translate-y-0.5">Hablar ahora <ArrowUpRight size={16}/></a>
      </motion.div>
    </div>
  </section>;
}

export function FutureStyleHomeMotion({ content }: { content: CmsContent }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [serviceIndex, setServiceIndex] = useState(0);
  const [projectIndex, setProjectIndex] = useState(0);
  const { base, sections } = content;
  const projects = sections.portfolio.data.slice(0, 3);
  const whatsapp = sections.header.data.whatsappLink;
  const service = services[serviceIndex];
  const project = projects[projectIndex];

  return <main className="future-motion min-h-screen overflow-hidden bg-[#070b12] text-white">
    <header className="fixed inset-x-0 top-0 z-50 px-4 py-4 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between rounded-full border border-white/15 bg-[#070b12]/55 px-5 py-3 backdrop-blur-xl"><Link href="/future" className="font-display text-xl tracking-[-.06em]">Aion<span className="text-[#ff6a3d]">Site</span></Link><nav className="hidden items-center gap-7 text-sm text-white/75 lg:flex"><a href="#servicios">Servicios</a><Link href="/proyectos">Proyectos</Link><a href="#historias">Historias</a><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-semibold text-[#070b12]"><MessageCircleMore size={15}/> Cotizar</a></nav><button type="button" className="rounded-full border border-white/15 p-2 lg:hidden" onClick={() => setMenuOpen((value) => !value)} aria-label="Menú">{menuOpen ? <X size={18}/> : <Menu size={18}/>}</button></div>{menuOpen && <div className="mx-auto mt-2 flex max-w-6xl flex-col gap-4 rounded-3xl border border-white/10 bg-[#0c131d] p-6 text-sm lg:hidden"><a href="#servicios">Servicios</a><Link href="/proyectos">Proyectos</Link><a href="#historias">Historias</a><a href={whatsapp} target="_blank" rel="noreferrer">Cotizar →</a></div>}</header>

    <section className="relative flex min-h-screen items-center justify-center px-5 pb-20 pt-28 text-center"><div className="absolute inset-0 bg-[url('/media/aionsite-tech-background.gif')] bg-cover bg-center opacity-55 motion-safe:animate-[future-hero-drift_16s_ease-in-out_infinite_alternate]"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_38%,rgba(255,106,61,.36),transparent_30%),linear-gradient(180deg,rgba(7,11,18,.35),#070b12_94%)]"/><motion.div initial="hidden" animate="show" variants={{ hidden:{}, show:{ transition:{ staggerChildren:.12, delayChildren:.2 }}}} className="relative z-10 mx-auto max-w-5xl"><motion.p variants={{hidden:{opacity:0,y:25},show:{opacity:1,y:0}}} className="mb-6 text-xs uppercase tracking-[.28em] text-[#ffb09a]">AionSite / crecimiento digital</motion.p><motion.h1 variants={{hidden:{opacity:0,y:32},show:{opacity:1,y:0}}} className="font-[Georgia,serif] text-[clamp(3.5rem,9vw,8rem)] leading-[.88] tracking-[-.07em]">Tu presencia online, <em className="font-normal text-[#ff8b68]">reimaginada.</em></motion.h1><motion.p variants={{hidden:{opacity:0,y:25},show:{opacity:1,y:0}}} className="mx-auto mt-8 max-w-2xl text-lg leading-relaxed text-white/75 sm:text-xl">Sitios web, tiendas y SEO con la claridad necesaria para ayudarte a avanzar.</motion.p><motion.div variants={{hidden:{opacity:0,y:25},show:{opacity:1,y:0}}} className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><a href={whatsapp} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-[#070b12]">Encuentra tu siguiente paso <ArrowRight size={17}/></a><a href="#servicios" className="text-sm text-white/75 underline decoration-[#ff6a3d] decoration-2 underline-offset-8">Ver cómo funciona</a></motion.div><motion.div variants={{hidden:{opacity:0,y:25},show:{opacity:1,y:0}}} className="mx-auto mt-20 grid max-w-3xl grid-cols-2 border-y border-white/15 py-5 text-left sm:grid-cols-4">{["Diseño con intención","SEO que se mide","IA responsable","Soporte continuo"].map((item,index)=><div key={item} className="border-white/15 px-3 py-2 text-xs text-white/60 sm:border-r last:border-0"><span className="mb-2 block text-2xl text-[#ff8b68]">0{index+1}</span>{item}</div>)}</motion.div></motion.div><div className="absolute bottom-6 left-1/2 -translate-x-1/2 text-xs uppercase tracking-[.25em] text-white/45">Desplaza para explorar</div></section>

    <ScaleSection className="bg-[#070b12] px-5 py-24 sm:px-10 lg:px-16 lg:py-32"><div id="servicios" className="mx-auto max-w-6xl"><div className="mb-14 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[.25em] text-[#ff8b68]">Juntos llegamos más lejos</p><h2 className="mt-5 max-w-4xl font-[Georgia,serif] text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">Una presencia digital que trabaja contigo.</h2></div><p className="max-w-xs text-sm leading-relaxed text-white/55">Todo lo que necesitas para que tu negocio se vea, se entienda y se elija.</p></div><div className="grid gap-5 lg:grid-cols-[1fr_1.4fr]"><div className="flex gap-2 lg:flex-col lg:justify-end">{services.map((item,index)=><button key={item[0]} type="button" aria-label={`Mostrar ${item[0]}`} onClick={() => setServiceIndex(index)} className={`h-2 rounded-full transition-all duration-500 lg:h-auto lg:w-32 lg:rounded-full lg:border lg:px-4 lg:py-3 lg:text-left lg:text-xs ${index===serviceIndex?"w-10 bg-[#ff6a3d] text-white lg:border-[#ff6a3d]":"w-2 bg-white/20 text-white/45 lg:border-white/10"}`}>{index===serviceIndex && <span className="hidden lg:inline">0{index+1} / {item[0]}</span>}</button>)}</div><div className="min-h-[25rem] rounded-[1.75rem] border border-white/10 bg-gradient-to-br from-white/[.13] to-white/[.025] p-7 sm:p-10"><AnimatePresence mode="wait"><motion.div key={serviceIndex} initial={{opacity:0,x:35}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-35}} transition={{duration:.45}} className="flex h-full flex-col justify-between"><div className="flex justify-between"><span className="text-sm text-[#ff8b68]">0{serviceIndex+1}</span><span className="flex h-10 w-10 items-center justify-center rounded-full border border-white/15"><ArrowUpRight size={17}/></span></div><div><h3 className="max-w-xl font-[Georgia,serif] text-4xl leading-none tracking-[-.04em] sm:text-6xl">{service[0]}</h3><p className="mt-5 max-w-md text-base leading-relaxed text-white/55">{service[1]}</p></div></motion.div></AnimatePresence></div></div></div></ScaleSection>

    <ScaleSection className="bg-[#f2efe8] px-5 py-24 text-[#10151b] sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-xs uppercase tracking-[.25em] text-[#e95e39]">Un roadmap único para tu negocio</p><h2 className="mt-5 max-w-xl font-[Georgia,serif] text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">La ruta cambia. Tu dirección permanece.</h2><p className="mt-7 max-w-lg text-lg leading-relaxed text-[#10151b]/65">Partimos de tus objetivos, tu realidad y tus clientes. Después convertimos todo eso en una presencia que puede crecer contigo.</p><a href={whatsapp} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#10151b] px-5 py-3 text-sm font-semibold text-white">Empezar conversación <ArrowUpRight size={16}/></a></div><div className="relative overflow-hidden rounded-[2rem] bg-[#17222b] p-7 text-white sm:p-10"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#ff6a3d]/80 blur-2xl"/><p className="relative z-10 text-xs uppercase tracking-[.2em] text-[#ffb09a]">AionSite / tu mapa</p><div className="relative z-10 mt-20 grid gap-5 sm:grid-cols-2">{[["Objetivo","Ser fácil de elegir"],["Experiencia","Clara y confiable"],["Sistema","Web + SEO + IA"],["Siguiente acción","Crecer con intención"]].map(([label,value])=><div key={label}><p className="text-xs text-white/45">{label}</p><p className="mt-2 text-xl">{value}</p></div>)}</div></div></div></ScaleSection>

    <ScaleSection id="historias" className="bg-[#070b12] px-5 py-24 text-white sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="text-xs uppercase tracking-[.25em] text-[#ff8b68]">Historias reales</p><h2 className="mt-5 font-[Georgia,serif] text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">Resultados que se sienten.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[["Ahora podemos explicar nuestro valor en segundos.","Molotes"],["La web dejó de ser una tarjeta y se volvió un canal.","Search Atlas"],["Tenemos una base clara para seguir creciendo.","LinkGraph"]].map(([quote,name])=><article key={name} className="rounded-[1.5rem] border border-white/10 bg-white/[.05] p-7"><div className="mb-16 text-5xl text-[#ff8b68]">“</div><p className="min-h-24 font-[Georgia,serif] text-2xl leading-tight">{quote}</p><div className="mt-8 border-t border-white/10 pt-4"><p className="font-semibold">{name}</p><p className="mt-1 text-xs text-white/45">Cliente AionSite</p></div></article>)}</div></div></ScaleSection>

    <ScaleSection className="relative z-10 bg-[#f2efe8] px-5 py-24 text-[#10151b] sm:px-10 lg:px-16 lg:py-32"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between gap-6"><div><p className="text-xs uppercase tracking-[.25em] text-[#e95e39]">Proyectos</p><h2 className="mt-5 font-[Georgia,serif] text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">Hechos para avanzar.</h2></div><div className="flex gap-2"><button type="button" aria-label="Proyecto anterior" onClick={() => setProjectIndex((index) => (index + projects.length - 1) % projects.length)} className="flex h-10 w-10 items-center justify-center rounded-full border border-[#10151b]/20"><ArrowLeft size={16}/></button><button type="button" aria-label="Proyecto siguiente" onClick={() => setProjectIndex((index) => (index + 1) % projects.length)} className="flex h-10 w-10 items-center justify-center rounded-full bg-[#10151b] text-white"><ArrowRight size={16}/></button></div></div><div className="mt-12 overflow-hidden rounded-[1.75rem]"><AnimatePresence mode="wait"><motion.div key={projectIndex} initial={{opacity:0,x:50}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-50}} transition={{duration:.5}}><Link href={project.url} target="_blank" rel="noreferrer" className="group relative block aspect-[1.8] overflow-hidden rounded-[1.75rem] bg-[#d8d2c7]"><Image src={project.image} alt={project.title} fill className="object-cover transition-transform duration-700 group-hover:scale-105" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"/><div className="absolute bottom-7 left-7 text-white sm:bottom-10 sm:left-10"><p className="text-xs uppercase tracking-[.18em] text-white/65">{project.category}</p><p className="mt-2 font-[Georgia,serif] text-4xl sm:text-6xl">{project.title}</p></div><span className="absolute right-6 top-6 flex h-12 w-12 items-center justify-center rounded-full bg-white text-[#10151b]"><ArrowUpRight size={18}/></span></Link></motion.div></AnimatePresence></div><div className="mt-5 flex gap-2">{projects.map((item,index)=><button key={item.title} type="button" aria-label={`Ver ${item.title}`} onClick={() => setProjectIndex(index)} className={`h-1.5 rounded-full transition-all ${index===projectIndex?"w-12 bg-[#e95e39]":"w-6 bg-[#10151b]/15"}`}/>)}</div></div></ScaleSection>

    <FinalStickyCta whatsapp={whatsapp}/><footer className="mx-auto flex max-w-6xl justify-between px-5 py-8 text-xs text-white/45 sm:px-10 lg:px-16"><span>{base.name} / diseño web, SEO e IA</span><span>© {new Date().getFullYear()} AionSite</span></footer>
  </main>;
}
